SawadaAoi/UniBoooom_repository

DX22Base/DX22Base.vcxproj, DX22Base/DX22Base.vcxproj.filters
=> Explosion(h.cpp)の追加

DX22Base/DX22Base.vcxproj, DX22Base/DX22Base.vcxproj.filters, DX22Base/Pos.cpp, DX22Base/Pos.h, DX22Base/TriType.cpp, DX22Base/TriType.h
Infoフィルタとテンプレート(同じ型を３つ持つテンプレートクラス、位置座標を管理するテンプレートクラス)を追加
=> テンプレート型の追加

DX22Base/SceneGame.cpp
=> 画面表示のカメラ位置がおかしいので修正

DX22Base/DX22Base.vcxproj, DX22Base/DX22Base.vcxproj.filters, DX22Base/Hammer.cpp, DX22Base/Hammer.h, DX22Base/Player.cpp, DX22Base/Player.h
=> PlayerとHammerのh,cppの追加

DX22Base/Collision.cpp, DX22Base/Collision.h, DX22Base/DX22Base.vcxproj, DX22Base/DX22Base.vcxproj.filters
=> 衝突判定用のCollision.cpp、Collision.hの追加

DX22Base/DX22Base.vcxproj.filters
Explosionのh,cppがvisual studio上でうまく表示されない不具合の修正
=> フィルター設定の修正

DX22Base/Collision.h
=> Collisionの修正

DX22Base/Explosion.cpp
Explosion.cppからSlimeManager.hを削除
=> Explosion.cppからSlimeManager.hを削除

DX22Base/SceneGame.cpp, DX22Base/SlimeBase.cpp, DX22Base/SlimeBase.h, DX22Base/SlimeManager.cpp
SlimeBase.hにあった定数をSlime.cppに移動。
SlimeBaseのhとcppに抜けていたコメントを追加。
SceneGame.cppにある爆発用のポインタが動的確保せずにDrawしていたのでDrawをコメントアウト
=> SlimeBaseに反発の関数を追加。

DX22Base/Hammer.cpp, DX22Base/Hammer.h, DX22Base/Player.cpp, DX22Base/Player.h, DX22Base/SceneGame.cpp
Info関係の変更でPos.hがなくなりPos3dとPos2dに分けられたのでPlayer、Hammer、SceneGameのIncludeと変数の型を修正
=> 実行できなくなっていたので修正

DX22Base/Controller.cpp, DX22Base/Input.cpp, DX22Base/Player.cpp, DX22Base/Player.h
コントローラ入力(directInput)が出来るようにプレイヤーCPPに処理を追加
=> コントローラ入力処理を変更する

DX22Base/Camera.cpp, DX22Base/Explosion.cpp, DX22Base/GameParameter.h, DX22Base/Main.cpp, DX22Base/Player.cpp, DX22Base/Player.h, DX22Base/SceneGameCollision.cpp, DX22Base/SlimeBase.cpp, DX22Base/SlimeBase.h, DX22Base/SlimeManager.cpp, DX22Base/SlimeManager.h, DX22Base/Slime_1.cpp, DX22Base/Slime_1.h, DX22Base/Slime_2.cpp, DX22Base/Slime_2.h, DX22Base/Slime_3.cpp, DX22Base/Slime_3.h, DX22Base/Slime_4.cpp, DX22Base/Slime_4.h
スライムのランダム移動
ゲーム開始時に一定数敵を生成する
スライムの衝突判定の処理内容を修正
=> Feature slime sawada

DX22Base/DX22Base.vcxproj.filters
=> フィルターバグの修正

DX22Base/Main.cpp, DX22Base/Main.h, DX22Base/Startup.cpp
Main.hにデバッグモードを定義し、これがtrueのときシーンマネージャを使用するようにしました。
このデバッグモードはプッシュ時falseにしてあるのでだれにも影響を与えません。
もしこれを使用したい場合はプル時にこのデバッグモードをtrueに書き換える必要があります。
Sceneまわりは触っていないので先刻あげたシーンのリクエストとの競合は起きません。
フィルターも触っていません。
=> ScceneManager使用

DX22Base/Camera.cpp, DX22Base/GameParameter.h, DX22Base/HitStop.cpp, DX22Base/SceneGame.cpp, DX22Base/SlimeManager.cpp, DX22Base/Transform3d.h
・赤赤の爆発生成時にヒットストップと画面揺れするように修正
・カメラの定数を一時的にGameParameter.hに移した
=> ヒットストップ＆振動処理を追加

DX22Base/SlimeManager.cpp
=> 小さいスライムにも爆発時に振動追加

DX22Base/GameParameter.h, DX22Base/SlimeManager.cpp
振動の数字を調整通りに。
ついでに火スライムと赤スライムの衝突時振動強化。
=> プランナーの振動調性案を実装

DX22Base/Stage1.cpp
=> ゲーム開始時のスタート合図の修正

DX22Base/GameParameter.h, DX22Base/SlimeManager.cpp
=> Feature fix vibrate col tkg

DX22Base/GameParameter.h, DX22Base/Hammer.cpp, DX22Base/Hammer.h, DX22Base/Player.cpp
振ると次振るときまでの間隔を長くしていたが
それを振ると振るスピードが遅くなるように変更しました
=> インターバルをスイングスピードに変更

DX22Base/Camera.cpp, DX22Base/Camera.h, DX22Base/GameParameter.h
=> Feature cnt vibrate change tkg

DX22Base/Scene.cpp
カメラがないとUIが出ない仕様にしたらタイトルのUIが出なくなっていたので緊急で対応しました。
=> タイトルのUIが出ない不具合を修正

DX22Base/Slime_3.cpp
=> 黄色スライムの挙動の修正

DX22Base/Stage.cpp, DX22Base/Stage1.cpp, DX22Base/Stage2.cpp, DX22Base/Stage3.cpp
デバッグモードを削除したときにポーズが消えてしまっていたので、その問題を解消
=> ステージにデバッグモード削除を反映

DX22Base/Result.cpp, DX22Base/StageFinishUI.h
佐々木先生の確認間に合わせ様に雑な処理で実装したので後で直す
=> リザルト画面クリア時のスタンプを雑実装

DX22Base/Union.cpp, DX22Base/Union.h, DX22Base/UnionManager.cpp
=> UNION仕様変更しました

DX22Base/Pause.cpp
=> ポーズ画面のキー操作追加

DX22Base/SelectStage.cpp, DX22Base/SelectStage.h
=> スティック入力時no

DX22Base/SlimeBase.cpp, DX22Base/SlimeBase.h, DX22Base/SlimeManager.cpp
=> デビルスライム着地硬直時の周りのスライムをボスの方向を向くように修正

DX22Base/Combo.cpp, DX22Base/Combo.h, DX22Base/ExplosionManager.cpp, DX22Base/SceneGame.cpp, DX22Base/Stage.cpp, DX22Base/Stage.h, DX22Base/Stage1.cpp, DX22Base/Stage2.cpp, DX22Base/Stage3.cpp, DX22Base/StageFinishUI.cpp, DX22Base/TotalScore.cpp, DX22Base/TotalScore.h, DX22Base/UIStageManager.cpp, DX22Base/UIStageManager.h
ゲーム終了間際の加算スコアがトータルスコアに反映されるように。
-TortalScoreにプレイヤーとタイマーの情報を渡した。
=> ゲーム終了間際の加算スコアがトータルスコアに反映されるように

DX22Base/Title.cpp, DX22Base/TitleBgPlayer.cpp, DX22Base/TitleBgPlayer.h
=> タイトルテクスチャ読み込みタイミング？

DX22Base/Title.cpp
=> コマンド選択バグ修正

DX22Base/TitleCommand.cpp, DX22Base/TitleCommand.h
=> コマンド系の動き変更

DX22Base/Pause.cpp
=> ポーズコマンドSE修正

DX22Base/SelectStage.cpp, DX22Base/SelectStage.h
=> セレクトー戻るSE追加

DX22Base/AnimeModel.cpp, DX22Base/Defines.h, DX22Base/Main.cpp, DX22Base/Main.h, DX22Base/Model.cpp, DX22Base/_model.cpp
=> Release適合処理

DX22Base/BattleData.cpp
=> バトルデータの初期化
